version: "3.6"
services:
  nginx:
    image: "${PROJECT_NAME}-nginx:latest"
    restart: always
    build:
      context: "${DOCKERFILE_PWD}/nginx"
      dockerfile: "./Dockerfile"
    volumes:
      - "${APP_PWD}:/app"
      - "${APP_PWD}/html:/html"
      - "${DOCKERFILE_PWD}/nginx/template.conf.d:/etc/nginx/conf.d/template"
    expose:
      - "80"
    environment:
      - "APP_ENV=${APP_ENV}"
      - "DOMAIN=${DOMAIN}"
      - "HTML_ERROR_PWD=/html/error"
      - "APP_WEB_ROOT=/app/html/web"
      - "CONFIG_TEMPLATE_NAME=yii2"
    labels:
      - "traefik.backend=nginx"
      - "traefik.frontend.rule=Host:${DOMAIN}"
    command: /bin/bash -c "envsubst '$${DOMAIN} $${APP_WEB_ROOT} $${HTML_ERROR_PWD}' < /etc/nginx/conf.d/template/${CONFIG_TEMPLATE_NAME}.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
