version: "3.6"
services:
  frontend:
    image: "nginx:latest"
    restart: always
    build:
      context: "${DOCKER_PWD}/dockerfile/nginx"
      dockerfile: "./Dockerfile"
    volumes:
      - "${PROJECT_PWD}/app:/app"
      - "${DOCKER_PWD}/dockerfile/nginx/html:/html"
      - "${DOCKER_PWD}/dockerfile/nginx/template.conf.d:/etc/nginx/conf.d/template"
    expose:
      - "80"
    environment:
      - "APP_ENV=${APP_ENV}"
      - "DOMAIN=${DOMAIN}"
      - "HTML_ERROR_PWD=/html/error"
      - "APP_WEB_ROOT=/app/html/web"
      - "CONFIG_TEMPLATE_NAME=yii2"
    labels:
      - "traefik.backend=${SERVICE_NAME}"
      - "traefik.frontend.rule=Host:${SERVICE_NAME}.${DOMAIN}"
    command: /bin/bash -c "envsubst '$${DOMAIN} $${APP_WEB_ROOT} $${HTML_ERROR_PWD}' < /etc/nginx/conf.d/template/${CONFIG_TEMPLATE_NAME}.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
