version: "3.6"
services:
  php:
    image: "${PROJECT_NAME}-php:7.1-fpm"
    container_name: "${PROJECT_NAME}_php"
    build:
      context: "${DOCKERFILE_PWD}/php"
      dockerfile: "./Dockerfile"
      args:
        USER: "${USER}"
        USER_ID: "${USER_ID}"
    user: "${USER}"
    restart: always
    volumes:
      - "${APP_PWD}:/app"
      - "php_tmp:/tmp"
    environment:
      - "APP_ENV=${APP_ENV}"
      - "PHP_IDE_CONFIG=${PHP_IDE_CONFIG}"
      - "XDEBUG_CONFIG=${XDEBUG_CONFIG}"
      - "DOMAIN=${DOMAIN}"
    labels:
      - "traefik.backend=php"
volumes:
  php_tmp:
    driver: local