version: "3.6"
services:
  postgres:
    image: "postgres:latest"
    container_name: "postgres"
    restart: always
    build:
      context: "${DOCKER_PWD}/dockerfile/postgres"
      dockerfile: "./Dockerfile"
    volumes:
      - "postgres_db:/var/lib/postgresql/data"
      - "postgres_db_backup:/backup/"
    env_file:
      - "${DOCKER_PDW}/source/postgres/env/db_living.env"
      - "${DOCKER_PDW}/source/postgres/env/selectel.env"
    environment:
      - "APP_ENV=${APP_ENV}"
    expose:
      - "5432"
    labels:
      - "traefik.backend=postgres"
volumes:
  postgres_db:
    external: false
  postgres_db_backup:
    external: false