version: "3.6"
services:
  postgres:
    image: "${PROJECT_NAME}-postgres:11"
    container_name: "${PROJECT_NAME}_postgres"
    restart: always
    build:
      context: "${DOCKERFILE_PWD}/postgres"
      dockerfile: "./Dockerfile"
    volumes:
      - "postgres_db:/var/lib/postgresql/data"
      - "postgres_db_backup:/backup/"
    env_file:
      - "${DOCKERFILE_PWD}/postgres/env/db.env"
    environment:
      - "APP_ENV=${APP_ENV}"
    expose:
      - "5432"
    labels:
      - "traefik.backend=postgres"
volumes:
  postgres_db:
    driver: local
  postgres_db_backup:
    driver: local