version: "3.6"
services:
  static:
    image: "${PROJECT_NAME}-static:latest"
    restart: always
    build:
      context: "${DOCKERFILE_PWD}/openresty"
      dockerfile: "./Dockerfile"
    volumes:
      - "${DOCKERFILE_PWD}/openresty/conf.d:/etc/nginx/conf.d"
      - "${APP_PWD}/lua:/lua"
      - "${APP_PWD}/html:/html"
    expose:
      - "80"
    environment:
      - "APP_ENV=${APP_ENV}"
      - "DOMAIN=static.${DOMAIN}"
      - "IMAGES_PWD=/static"
      - "HTML_PWD=/html"
      - "LUA_PWD=/lua"
      - "LUA_CODE_CACHE=no"
    labels:
      - "traefik.backend=static"
      - "traefik.frontend.rule=Host:static.${DOMAIN}"
    command: /bin/bash -c "envsubst '$${DOMAIN} $${IMAGES_PWD} $${HTML_PWD} $${LUA_PWD} $${LUA_CODE_CACHE}' < /etc/nginx/conf.d/conf.template > /etc/nginx/conf.d/default.conf && /usr/local/openresty/bin/openresty -g 'daemon off;'"