version: '3.6'
services:

  server:
    image: "jetbrains/teamcity-server:latest"
    container_name: "teamcity_server"
    environment:
      TEAMCITY_SERVER_MEM_OPTS: "-Xmx2g -XX:MaxPermSize=270m -XX:ReservedCodeCacheSize=350m"
    ports:
      - "18782:8111"
    volumes:
      - "data:/data/teamcity_server/datadir"
      - "logs:/opt/teamcity/logs"
    labels:
      - "traefik.backend=teamcity_server"
      - "traefik.frontend.rule=Host:teamcity.${DOMAIN}"
    restart: always
    depends_on:
      - db

  db:
    image: "postgres:10.4"
    container_name: "teamcity_db"
    restart: always
    volumes:
      - "db_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "root"
      POSTGRES_DB: "teamcity_db"
    expose:
      - "5432"

volumes:
  data:
    driver: local
  logs:
    driver: local
  db_data:
    driver: local

networks:
  default:
    external:
      name: teamcity